version: "3.8"

services:
    php:
        image: composer:latest # First use composer image to install dependencies
        container_name: php-composer
        volumes:
            - .:/var/www/app
        working_dir: /var/www/app
        command: composer install
        networks:
            - laravel

    php-fpm:
        image: ghcr.io/channlyva/core-api:latest
        container_name: php
        restart: unless-stopped
        ports:
            - "9000:9000"
        networks:
            - laravel
        volumes:
            - .:/var/www/app:delegated
        depends_on:
            mysql:
                condition: service_healthy
            php:
                condition: service_completed_successfully
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: api
            DB_USERNAME: laravel
            DB_PASSWORD: root
        healthcheck:
            test: ["CMD", "php", "artisan", "--version"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
        command: php-fpm

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/app:delegated
        depends_on:
            - php-fpm
        networks:
            - laravel

    mysql:
        image: mysql:8
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: api
            MYSQL_USER: laravel
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-proot",
                ]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s

volumes:
    db_data:

networks:
    laravel:
