version: "3.8"

services:
    php-fpm:
        image: ghcr.io/channlyva/core-api:latest
        container_name: php-fpm
        restart: unless-stopped
        networks:
            - laravel
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: api
            DB_USERNAME: laravel
            DB_PASSWORD: root
        healthcheck:
            test: ["CMD", "php", "artisan", "--version"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
        command: php-fpm

    webserver:
        image: nginx:alpine
        container_name: nginx_web
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./news:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
        networks:
            - laravel

    mysql:
        image: mysql:8
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: api
            MYSQL_USER: laravel
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

volumes:
    db_data:

networks:
    laravel:
