version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - news_network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: news_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - news_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: news_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:api}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:root}
      MYSQL_PASSWORD: ${DB_PASSWORD:root}
      MYSQL_USER: ${DB_USERNAME:core-api}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - news_network

networks:
  news_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
