version: "3.8"

services:
    app:
        image: ghcr.io/channlyva/core-api:latest
        container_name: laravel_app
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
        networks:
            - laravel
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: api
            DB_USERNAME: root
            DB_PASSWORD: root

    webserver:
        image: nginx:alpine
        container_name: nginx_web
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:8
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: api
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-proot",
                ]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s

volumes:
    db_data:

networks:
    laravel:
